import 'package:flutter/widgets.dart';

import 'app_config.dart';
import 'app_state.dart';

class Lang {
  final String code;
  final String native;
  final String english;
  final String flag;
  const Lang(this.code, this.native, this.english, this.flag);
}

/// Order used on the onboarding "Choose your language" screen.
const List<Lang> kLanguages = [
  Lang('en', 'English', 'English', '🇬🇧'),
  Lang('es', 'Español', 'Spanish', '🇪🇸'),
  Lang('pt', 'Português', 'Portuguese', '🇵🇹'),
  Lang('fr', 'Français', 'French', '🇫🇷'),
  Lang('de', 'Deutsch', 'German', '🇩🇪'),
  Lang('vi', 'Tiếng Việt', 'Vietnamese', '🇻🇳'),
  Lang('id', 'Bahasa Indonesia', 'Indonesian', '🇮🇩'),
  Lang('hi', 'हिन्दी', 'Hindi', '🇮🇳'),
];

/// Order used on the Settings > Language screen.
const List<String> kSettingsLangOrder = [
  'en', 'de', 'pt', 'es', 'fr', 'id', 'hi', 'vi'
];

Lang langByCode(String code) =>
    kLanguages.firstWhere((l) => l.code == code, orElse: () => kLanguages[0]);

/// Translate [key] into the current language. Rebuilds on language change.
String tr(BuildContext context, String key, [Map<String, String>? args]) {
  final code = AppScope.of(context).lang;
  var s = _t[code]?[key] ?? _t['en']![key] ?? key;
  s = s.replaceAll('{app}', AppConfig.appName);
  args?.forEach((k, v) => s = s.replaceAll('{$k}', v));
  return s;
}

const Map<String, Map<String, String>> _t = {
  'en': {
    'loading': 'Loading',
    'tagline': 'Draw together',
    'chooseLanguage': 'Choose your language',
    'changeAnytime': 'You can change this anytime in Settings',
    'continue': 'Continue',
    'ageTitle': 'Let us know your age',
    'ageSub': 'To start your creative journey!',
    'year': 'year',
    'purposeTitle': 'So, what brings you in today?',
    'purposeSub': 'Pick the one that fits you best',
    'p_relax': 'Relax and reduce stress',
    'p_connect': 'Connect and draw with others',
    'p_improve': 'Improve my drawing skills',
    'p_kids': 'To teach my kids to draw',
    'p_health': 'Recover from health issues',
    'p_other': 'Other',
    'interestsTitle': 'Tell us what interests you',
    'interestsSub': 'Select at least 1 option',
    'i_animal': 'Animal',
    'i_food': 'Food',
    'i_cartoon': 'Cartoon',
    'i_anime': 'Anime',
    'i_kpop': 'K-Pop Idols',
    'i_plant': 'Plant',
    'i_worldcup': 'World Cup',
    'i_seasonal': 'Seasonal',
    'goodMorning': 'Good morning',
    'goodAfternoon': 'Good afternoon',
    'goodEvening': 'Good evening',
    'premium': 'Premium',
    'profile': 'Profile',
    'spentTime': 'Spent time',
    'lesson': 'Lesson',
    'yourLevel': 'Your Level',
    'levels': 'Levels',
    'levelDesc': 'Complete lessons to level up!',
    'lessonsNeeded': '{n} lessons',
    'myBuddies': 'My buddies',
    'buddiesCount': '{n} buddies',
    'noBuddies': 'No buddies yet. Draw together with others to make friends!',
    'myAlbum': 'My album',
    'favorite': 'Favorite',
    'sortNewest': 'Sort by Newest',
    'sortOldest': 'Sort by Oldest',
    'drawNow': 'Draw Now',
    'setting': 'Setting',
    'turnOffMessages': 'Turn off messages',
    'music': 'Music',
    'soundFx': 'Sound Fx',
    'vibrate': 'Vibrate',
    'language': 'Language',
    'share': 'Share to your friends',
    'rate': 'Rate 5 stars',
    'feedback': 'Feedback',
    'policy': 'Policy',
    'checkUpdate': 'Check for update',
    'rateTitle': 'Do you like this application?',
    'rateSub': 'Your rating will help us make the application even better.',
    'rateUs': 'Rate US',
    'thanksRating': 'Thanks for your rating!',
    'comingSoon': 'Coming soon!',
    'editName': 'Edit name',
    'chooseAvatar': 'Choose avatar',
    'save': 'Save',
    'cancel': 'Cancel',
    'shareText': "Let's draw together on {app}! Download it here: {url}",
    'feedbackSubject': 'Feedback for {app}',
    'cantOpen': 'Could not open the link',
    'lv_novice': 'Novice',
    'lv_apprentice': 'Apprentice',
    'lv_budding': 'Budding',
    'lv_emerging': 'Emerging',
    'lv_developing': 'Developing',
    'lv_skilled': 'Skilled',
    'lv_proficient': 'Proficient',
    'lv_accomplished': 'Accomplished',
    'lv_master': 'Master',
    'lv_expert': 'Expert',
    'lv_virtuoso': 'Virtuoso',
    'lv_legendary': 'Legendary',
    'unlockHint': 'Complete {n} lessons to unlock',
    'levelUnlocked': 'Unlocked!',
    'drawTogether': 'Draw Together',
    'quickMatch': 'Quick Match',
    'randomPlayer': 'Random Player',
    'privateMatch': 'Private Match',
    'withFriends': 'With Friends',
    'popular': 'Popular',
    'draw': 'Draw',
    'traceArt': 'Trace Art',
    'c_beginner': 'Beginner',
    'c_trending': 'Trending',
    'c_neon': 'Neon',
    'c_xmas': 'Xmas',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Trace the picture first!',
    'greatJob': 'Great job!',
    'lessonDone': '+1 lesson completed. Keep drawing to level up!',
    'selectRoom': 'Select Room',
    'players4': '4 Players',
    'players2': '2 Players',
    'selectTemplate': 'Select Template',
    'findingPlayers': 'Finding Other\nPlayers',
    'searching': 'Searching',
    'matched': 'YOU\u2019VE BEEN\nMATCHED',
    'leaveTitle': 'Do you want to leave?',
    'stillDrawing': 'STILL DRAWING',
    'quit': 'Quit',
    'strokeWrong': 'You need to draw the current stroke correctly',
    'colorNow': 'Outline done! Color it in, then tap →',
    'waitingOthers': 'Waiting for other players...',
    'results': 'Results',
    'ourArtwork': 'Our artwork',
    'playAgain': 'Play Again',
    'home': 'Home',
    'you': 'You',
    'accuracy': 'Accuracy',
    'leftGame': 'Left',
    'yourPart': 'Your part is highlighted',
    'preview': 'Preview',
    'savedToAlbum': '+1 lesson! Your drawing is saved in My album.',
    'sound': 'Sound',
    'exitDrawing': 'Exit Drawing',
    'colorMore': 'Color more of the highlighted area',
    'perfectDrawing': 'Perfect Drawing',
    'greatDrawing': 'Great Drawing',
    'goodDrawing': 'Nice Drawing',
    'point': 'Point',
    'lines': 'Lines',
    'time': 'Time',
    'shareShort': 'Share',
    'drawAgain': 'Draw Again',
    'savedGallery': 'Save image to gallery success!',
    'saveFailed': 'Something went wrong! Please try again later.',
    'tellUsTitle': 'Tell Us What You Need',
    'tellUsSub': 'Let us know your ideas or issues',
    'requestFeature': 'Request Feature',
    'reportBug': 'Report Bug',
    'c_character': 'Character',
    'c_plant': 'Plant',
    'justNow': 'just now',
    'minutesAgo': '{n} min ago',
    'hoursAgo': '{n} h ago',
    'daysAgo': '{n} d ago',
    'noBuddiesYet': 'No buddies yet',
    'noBuddiesSub': 'Draw with someone to add your first buddy',
    'findNewBuddy': 'Find a new buddy',
    'drewTogether': 'Drew together',
    'findingBuddies': 'Finding drawing buddies...',
    'readyToDraw': 'Ready to draw!',
    'readyWord': 'ready',
    'waiting': 'Waiting...',
    'startingIn': 'Starting in {n}...',
    'drawingPartner': 'Drawing Partner',
    'doneWord': 'Done',
    'drawingWord': 'Drawing',
    'premiumSub': 'Loved by young artists everywhere',
    'featNoAds': 'No ads Drawing',
    'featNewContent': 'New Content Every Week',
    'featSupport': 'Customer Support',
    'yearly': 'Yearly',
    'weekly': 'Weekly',
    'save90': 'Save 90%',
    'justPerYear': 'Just {p}/year',
    'weekShort': 'week',
    'processing': 'Processing...',
    'cancelAnytime': 'Cancel Anytime',
    'subDisclaimer': 'Payment will start after the free trial period ends. Cancel your subscription before the end of the trial to avoid being charged. The subscription will automatically renew until you cancel it.',
    'privacy': 'Privacy',
    'terms': 'Terms',
    'restorePurchase': 'Restore Purchase',
    'nothingToRestore': 'There is nothing to restore.',
    'restoreSuccess': 'Your Premium has been restored!',
    'storeUnavailable': 'The store is not available right now. Please try again later.',
    'purchaseFailed': 'Purchase failed. Please try again.',
    'welcomePremium': 'Welcome to Premium! Enjoy drawing without ads.',
    'alreadyPremium': 'You already have Premium.',
    'premiumActive': 'Premium Active ✓',
    'productNotFound': 'Subscriptions are not set up in Google Play yet.',
    'othersNotFinished': 'Other users haven\'t finished',
    'allFinishedTap': 'Everyone finished! Tap →',
    'youAre1': 'YOU ARE 1st!',
    'youAre2': 'YOU ARE 2nd!',
    'youAre3': 'YOU ARE 3rd!',
    'youAre4': 'YOU ARE 4th!',
    'clearStepTitle': 'Clear This Step',
    'clearStepSub': 'Delete all the drawings on the artboard.',
    'clearWord': 'Clear',
    'rateForUs': 'Rate For Us',
    'rateForUsSub': 'Your rating helps us improve our lessons',
    'c_popular': 'Popular',
    'c_seasonal': 'Seasonal',
    'randomMatch': 'Random Match',
    'joinRoom': 'Join Room',
    'enterRoomCode': 'Enter room code',
    'roomCodeSub': '4-digit code from your friend',
    'pasteClipboard': 'Paste from clipboard',
    'roomNotFound': 'Room not found. Check the code and try again.',
    'inviteFriend': 'Invite a friend',
    'roomCodeTitle': 'Room code',
    'waitingFriend': 'Waiting for your friend...',
    'copyCode': 'Copy',
    'codeCopied': 'Code copied!',
    'shareCode': 'Draw with me in {app}! Open Draw Together → Join Room and enter code {code}',
    'joiningRoom': 'Joining room...',
    'inviteFriendBtn': 'Invite Friend',
    'createLobby': 'Create Lobby',
    'lobby': 'Lobby',
    'change': 'Change',
    'youHost': 'You · host',
    'invite': 'Invite',
    'roomCodeCaps': 'ROOM CODE',
    'roomCodeShare': 'Share the waiting room ID with friends.',
    'friendNearby': 'Got a friend nearby?',
    'sendCode': 'Send them the room code',
    'letsDraw': 'Let\'s draw!',
    'drawMyself': 'I\'ll draw by myself',
    'slotOpen': '1 slot still open',
    'pickHow': 'Pick how to start.',
    'fillNow': 'Fill them now',
    'waitFriends': 'Wait for friends',
    'findingBuddiesTitle': 'Finding buddies...',
    'stepsCount': '{n} steps',
    'notOnCamera': 'Not on camera',
    'friendStillDrawing': '{n} friend still drawing',
    'friendDone': 'Your buddy finished!',
    'noMessages': 'No messages yet',
    'sayHi': 'Say hi to your drawing buddies',
    'saySomething': 'Say something...',
    'react': 'React',
    'emojiTab': 'Emoji',
    'phraseTab': 'Phrase',
    'emojiOnly': 'Emoji & phrases only with new buddies',
    'choosePicture': 'Choose a picture',
    'friendJoined': '{name} joined!',
    'ph1': 'Hi! 👋',
    'ph2': 'Nice job!',
    'ph3': 'So cute!',
    'ph4': 'Let\'s go!',
    'ph5': 'Great colors!',
    'ph6': 'Almost done!',
    'ph7': 'Thank you!',
    'ph8': 'Well done! 🎉',
    'onlineNeeded': 'Inviting a friend needs the internet.',
  },
  'es': {
    'loading': 'Cargando',
    'tagline': 'Dibujemos juntos',
    'chooseLanguage': 'Elige tu idioma',
    'changeAnytime': 'Puedes cambiarlo en cualquier momento en Ajustes',
    'continue': 'Continuar',
    'ageTitle': 'Dinos tu edad',
    'ageSub': '¡Para empezar tu viaje creativo!',
    'year': 'años',
    'purposeTitle': '¿Qué te trae por aquí hoy?',
    'purposeSub': 'Elige la opción que mejor te describa',
    'p_relax': 'Relajarme y reducir el estrés',
    'p_connect': 'Conectar y dibujar con otros',
    'p_improve': 'Mejorar mis habilidades de dibujo',
    'p_kids': 'Enseñar a dibujar a mis hijos',
    'p_health': 'Recuperarme de problemas de salud',
    'p_other': 'Otro',
    'interestsTitle': 'Cuéntanos qué te interesa',
    'interestsSub': 'Selecciona al menos 1 opción',
    'i_animal': 'Animales',
    'i_food': 'Comida',
    'i_cartoon': 'Caricaturas',
    'i_anime': 'Anime',
    'i_kpop': 'Ídolos K-Pop',
    'i_plant': 'Plantas',
    'i_worldcup': 'Copa Mundial',
    'i_seasonal': 'De temporada',
    'goodMorning': 'Buenos días',
    'goodAfternoon': 'Buenas tardes',
    'goodEvening': 'Buenas noches',
    'premium': 'Premium',
    'profile': 'Perfil',
    'spentTime': 'Tiempo',
    'lesson': 'Lección',
    'yourLevel': 'Tu nivel',
    'levels': 'Niveles',
    'levelDesc': '¡Completa lecciones para subir de nivel!',
    'lessonsNeeded': '{n} lecciones',
    'myBuddies': 'Mis amigos',
    'buddiesCount': '{n} amigos',
    'noBuddies': 'Aún no tienes amigos. ¡Dibuja con otros para hacer amigos!',
    'myAlbum': 'Mi álbum',
    'favorite': 'Favoritos',
    'sortNewest': 'Más recientes',
    'sortOldest': 'Más antiguos',
    'drawNow': 'Dibujar',
    'setting': 'Ajustes',
    'turnOffMessages': 'Desactivar mensajes',
    'music': 'Música',
    'soundFx': 'Efectos',
    'vibrate': 'Vibración',
    'language': 'Idioma',
    'share': 'Compartir con amigos',
    'rate': 'Califica con 5 estrellas',
    'feedback': 'Comentarios',
    'policy': 'Política',
    'checkUpdate': 'Buscar actualización',
    'rateTitle': '¿Te gusta esta aplicación?',
    'rateSub': 'Tu calificación nos ayudará a mejorar la aplicación.',
    'rateUs': 'Calificar',
    'thanksRating': '¡Gracias por tu calificación!',
    'comingSoon': '¡Próximamente!',
    'editName': 'Editar nombre',
    'chooseAvatar': 'Elegir avatar',
    'save': 'Guardar',
    'cancel': 'Cancelar',
    'shareText': '¡Dibujemos juntos en {app}! Descárgala aquí: {url}',
    'feedbackSubject': 'Comentarios para {app}',
    'cantOpen': 'No se pudo abrir el enlace',
    'lv_novice': 'Novato',
    'lv_apprentice': 'Aprendiz',
    'lv_budding': 'En ciernes',
    'lv_emerging': 'Emergente',
    'lv_developing': 'En desarrollo',
    'lv_skilled': 'Hábil',
    'lv_proficient': 'Competente',
    'lv_accomplished': 'Consumado',
    'lv_master': 'Maestro',
    'lv_expert': 'Experto',
    'lv_virtuoso': 'Virtuoso',
    'lv_legendary': 'Legendario',
    'unlockHint': 'Completa {n} lecciones para desbloquear',
    'levelUnlocked': '¡Desbloqueado!',
    'drawTogether': 'Dibujar juntos',
    'quickMatch': 'Partida rápida',
    'randomPlayer': 'Jugador aleatorio',
    'privateMatch': 'Partida privada',
    'withFriends': 'Con amigos',
    'popular': 'Popular',
    'draw': 'Dibujar',
    'traceArt': 'Calcar arte',
    'c_beginner': 'Principiante',
    'c_trending': 'Tendencia',
    'c_neon': 'Neón',
    'c_xmas': 'Navidad',
    'c_halloween': 'Halloween',
    'emptyDrawing': '¡Primero calca el dibujo!',
    'greatJob': '¡Buen trabajo!',
    'lessonDone': '+1 lección completada. ¡Sigue dibujando para subir de nivel!',
    'selectRoom': 'Elegir sala',
    'players4': '4 jugadores',
    'players2': '2 jugadores',
    'selectTemplate': 'Elegir plantilla',
    'findingPlayers': 'Buscando otros\njugadores',
    'searching': 'Buscando',
    'matched': '¡YA TIENES\nPAREJA!',
    'leaveTitle': '¿Quieres salir?',
    'stillDrawing': 'SEGUIR DIBUJANDO',
    'quit': 'Salir',
    'strokeWrong': 'Debes dibujar el trazo actual correctamente',
    'colorNow': '¡Contorno listo! Coloréalo y toca →',
    'waitingOthers': 'Esperando a los demás jugadores...',
    'results': 'Resultados',
    'ourArtwork': 'Nuestra obra',
    'playAgain': 'Jugar de nuevo',
    'home': 'Inicio',
    'you': 'Tú',
    'accuracy': 'Precisión',
    'leftGame': 'Salió',
    'yourPart': 'Tu parte está resaltada',
    'preview': 'Vista previa',
    'savedToAlbum': '¡+1 lección! Tu dibujo se guardó en Mi álbum.',
    'sound': 'Sonido',
    'exitDrawing': 'Salir del dibujo',
    'colorMore': 'Colorea más la zona resaltada',
    'perfectDrawing': 'Dibujo perfecto',
    'greatDrawing': 'Gran dibujo',
    'goodDrawing': 'Buen dibujo',
    'point': 'Puntos',
    'lines': 'Trazos',
    'time': 'Tiempo',
    'shareShort': 'Compartir',
    'drawAgain': 'Dibujar otra vez',
    'savedGallery': '¡Imagen guardada en la galería!',
    'saveFailed': '¡Algo salió mal! Inténtalo más tarde.',
    'tellUsTitle': 'Dinos lo que necesitas',
    'tellUsSub': 'Cuéntanos tus ideas o problemas',
    'requestFeature': 'Pedir función',
    'reportBug': 'Reportar error',
    'c_character': 'Personajes',
    'c_plant': 'Plantas',
    'justNow': 'ahora',
    'minutesAgo': 'hace {n} min',
    'hoursAgo': 'hace {n} h',
    'daysAgo': 'hace {n} d',
    'noBuddiesYet': 'Aún no tienes amigos',
    'noBuddiesSub': 'Dibuja con alguien para añadir tu primer amigo',
    'findNewBuddy': 'Buscar un nuevo amigo',
    'drewTogether': 'Dibujaron juntos',
    'findingBuddies': 'Buscando compañeros de dibujo...',
    'readyToDraw': '¡Listos para dibujar!',
    'readyWord': 'listos',
    'waiting': 'Esperando...',
    'startingIn': 'Empieza en {n}...',
    'drawingPartner': 'Compañero de dibujo',
    'doneWord': 'Listo',
    'drawingWord': 'Dibujando',
    'premiumSub': 'Favorito de pequeños artistas',
    'featNoAds': 'Dibujo sin anuncios',
    'featNewContent': 'Contenido nuevo cada semana',
    'featSupport': 'Atención al cliente',
    'yearly': 'Anual',
    'weekly': 'Semanal',
    'save90': 'Ahorra 90%',
    'justPerYear': 'Solo {p}/año',
    'weekShort': 'semana',
    'processing': 'Procesando...',
    'cancelAnytime': 'Cancela cuando quieras',
    'subDisclaimer': 'El pago comenzará al terminar la prueba gratuita. Cancela antes del final de la prueba para evitar cargos. La suscripción se renovará automáticamente hasta que la canceles.',
    'privacy': 'Privacidad',
    'terms': 'Términos',
    'restorePurchase': 'Restaurar compra',
    'nothingToRestore': 'No hay nada que restaurar.',
    'restoreSuccess': '¡Tu Premium se ha restaurado!',
    'storeUnavailable': 'La tienda no está disponible ahora. Inténtalo más tarde.',
    'purchaseFailed': 'La compra falló. Inténtalo de nuevo.',
    'welcomePremium': '¡Bienvenido a Premium! Dibuja sin anuncios.',
    'alreadyPremium': 'Ya tienes Premium.',
    'premiumActive': 'Premium activo ✓',
    'productNotFound': 'Las suscripciones aún no están configuradas en Google Play.',
    'othersNotFinished': 'Los demás aún no han terminado',
    'allFinishedTap': '¡Todos terminaron! Toca →',
    'youAre1': '¡ERES 1.º!',
    'youAre2': '¡ERES 2.º!',
    'youAre3': '¡ERES 3.º!',
    'youAre4': '¡ERES 4.º!',
    'clearStepTitle': 'Borrar este paso',
    'clearStepSub': 'Borra todos los dibujos del lienzo.',
    'clearWord': 'Borrar',
    'rateForUs': 'Califícanos',
    'rateForUsSub': 'Tu calificación nos ayuda a mejorar las lecciones',
    'c_popular': 'Popular',
    'c_seasonal': 'Temporada',
    'randomMatch': 'Partida aleatoria',
    'joinRoom': 'Unirse a sala',
    'enterRoomCode': 'Introduce el código',
    'roomCodeSub': 'Código de 4 dígitos de tu amigo',
    'pasteClipboard': 'Pegar del portapapeles',
    'roomNotFound': 'Sala no encontrada. Revisa el código e inténtalo de nuevo.',
    'inviteFriend': 'Invitar a un amigo',
    'roomCodeTitle': 'Código de sala',
    'waitingFriend': 'Esperando a tu amigo...',
    'copyCode': 'Copiar',
    'codeCopied': '¡Código copiado!',
    'shareCode': '¡Dibuja conmigo en {app}! Abre Dibujar juntos → Unirse a sala e introduce el código {code}',
    'joiningRoom': 'Entrando a la sala...',
    'inviteFriendBtn': 'Invitar amigo',
    'createLobby': 'Crear sala',
    'lobby': 'Sala',
    'change': 'Cambiar',
    'youHost': 'Tú · anfitrión',
    'invite': 'Invitar',
    'roomCodeCaps': 'CÓDIGO DE SALA',
    'roomCodeShare': 'Comparte el ID de la sala con amigos.',
    'friendNearby': '¿Tienes un amigo cerca?',
    'sendCode': 'Envíale el código de sala',
    'letsDraw': '¡A dibujar!',
    'drawMyself': 'Dibujaré solo',
    'slotOpen': 'Queda 1 lugar libre',
    'pickHow': 'Elige cómo empezar.',
    'fillNow': 'Llenar ahora',
    'waitFriends': 'Esperar amigos',
    'findingBuddiesTitle': 'Buscando compañeros...',
    'stepsCount': '{n} pasos',
    'notOnCamera': 'Sin cámara',
    'friendStillDrawing': '{n} amigo sigue dibujando',
    'friendDone': '¡Tu compañero terminó!',
    'noMessages': 'Aún no hay mensajes',
    'sayHi': 'Saluda a tus compañeros de dibujo',
    'saySomething': 'Di algo...',
    'react': 'Reaccionar',
    'emojiTab': 'Emoji',
    'phraseTab': 'Frase',
    'emojiOnly': 'Solo emojis y frases con nuevos compañeros',
    'choosePicture': 'Elige un dibujo',
    'friendJoined': '¡{name} se unió!',
    'ph1': '¡Hola! 👋',
    'ph2': '¡Buen trabajo!',
    'ph3': '¡Qué lindo!',
    'ph4': '¡Vamos!',
    'ph5': '¡Qué colores!',
    'ph6': '¡Casi listo!',
    'ph7': '¡Gracias!',
    'ph8': '¡Muy bien! 🎉',
    'onlineNeeded': 'Invitar a un amigo necesita internet.',
  },
  'pt': {
    'loading': 'Carregando',
    'tagline': 'Desenhe junto',
    'chooseLanguage': 'Escolha seu idioma',
    'changeAnytime': 'Você pode mudar isso a qualquer momento em Configurações',
    'continue': 'Continuar',
    'ageTitle': 'Diga-nos sua idade',
    'ageSub': 'Para começar sua jornada criativa!',
    'year': 'anos',
    'purposeTitle': 'Então, o que traz você aqui hoje?',
    'purposeSub': 'Escolha a opção que mais combina com você',
    'p_relax': 'Relaxar e reduzir o estresse',
    'p_connect': 'Conectar e desenhar com outros',
    'p_improve': 'Melhorar minhas habilidades de desenho',
    'p_kids': 'Ensinar meus filhos a desenhar',
    'p_health': 'Recuperar de problemas de saúde',
    'p_other': 'Outro',
    'interestsTitle': 'Conte-nos o que te interessa',
    'interestsSub': 'Selecione pelo menos 1 opção',
    'i_animal': 'Animais',
    'i_food': 'Comida',
    'i_cartoon': 'Desenhos',
    'i_anime': 'Anime',
    'i_kpop': 'Ídolos K-Pop',
    'i_plant': 'Plantas',
    'i_worldcup': 'Copa do Mundo',
    'i_seasonal': 'Sazonal',
    'goodMorning': 'Bom dia',
    'goodAfternoon': 'Boa tarde',
    'goodEvening': 'Boa noite',
    'premium': 'Premium',
    'profile': 'Perfil',
    'spentTime': 'Tempo',
    'lesson': 'Lição',
    'yourLevel': 'Seu nível',
    'levels': 'Níveis',
    'levelDesc': 'Complete lições para subir de nível!',
    'lessonsNeeded': '{n} lições',
    'myBuddies': 'Meus amigos',
    'buddiesCount': '{n} amigos',
    'noBuddies': 'Ainda sem amigos. Desenhe com outros para fazer amigos!',
    'myAlbum': 'Meu álbum',
    'favorite': 'Favoritos',
    'sortNewest': 'Mais recentes',
    'sortOldest': 'Mais antigos',
    'drawNow': 'Desenhar',
    'setting': 'Configurações',
    'turnOffMessages': 'Desativar mensagens',
    'music': 'Música',
    'soundFx': 'Efeitos sonoros',
    'vibrate': 'Vibrar',
    'language': 'Idioma',
    'share': 'Compartilhar com amigos',
    'rate': 'Avalie com 5 estrelas',
    'feedback': 'Feedback',
    'policy': 'Política',
    'checkUpdate': 'Verificar atualização',
    'rateTitle': 'Você gosta deste aplicativo?',
    'rateSub': 'Sua avaliação nos ajudará a melhorar ainda mais o aplicativo.',
    'rateUs': 'Avaliar',
    'thanksRating': 'Obrigado pela sua avaliação!',
    'comingSoon': 'Em breve!',
    'editName': 'Editar nome',
    'chooseAvatar': 'Escolher avatar',
    'save': 'Salvar',
    'cancel': 'Cancelar',
    'shareText': 'Vamos desenhar juntos no {app}! Baixe aqui: {url}',
    'feedbackSubject': 'Feedback para {app}',
    'cantOpen': 'Não foi possível abrir o link',
    'lv_novice': 'Novato',
    'lv_apprentice': 'Aprendiz',
    'lv_budding': 'Iniciante',
    'lv_emerging': 'Emergente',
    'lv_developing': 'Em evolução',
    'lv_skilled': 'Habilidoso',
    'lv_proficient': 'Proficiente',
    'lv_accomplished': 'Talentoso',
    'lv_master': 'Mestre',
    'lv_expert': 'Especialista',
    'lv_virtuoso': 'Virtuoso',
    'lv_legendary': 'Lendário',
    'unlockHint': 'Complete {n} lições para desbloquear',
    'levelUnlocked': 'Desbloqueado!',
    'drawTogether': 'Desenhar juntos',
    'quickMatch': 'Partida rápida',
    'randomPlayer': 'Jogador aleatório',
    'privateMatch': 'Partida privada',
    'withFriends': 'Com amigos',
    'popular': 'Popular',
    'draw': 'Desenhar',
    'traceArt': 'Traçar arte',
    'c_beginner': 'Iniciante',
    'c_trending': 'Em alta',
    'c_neon': 'Neon',
    'c_xmas': 'Natal',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Primeiro trace o desenho!',
    'greatJob': 'Muito bem!',
    'lessonDone': '+1 lição concluída. Continue desenhando para subir de nível!',
    'selectRoom': 'Escolher sala',
    'players4': '4 jogadores',
    'players2': '2 jogadores',
    'selectTemplate': 'Escolher modelo',
    'findingPlayers': 'Procurando outros\njogadores',
    'searching': 'Procurando',
    'matched': 'PARTIDA\nENCONTRADA',
    'leaveTitle': 'Você quer sair?',
    'stillDrawing': 'CONTINUAR DESENHANDO',
    'quit': 'Sair',
    'strokeWrong': 'Você precisa desenhar o traço atual corretamente',
    'colorNow': 'Contorno pronto! Pinte e toque em →',
    'waitingOthers': 'Aguardando os outros jogadores...',
    'results': 'Resultados',
    'ourArtwork': 'Nossa arte',
    'playAgain': 'Jogar de novo',
    'home': 'Início',
    'you': 'Você',
    'accuracy': 'Precisão',
    'leftGame': 'Saiu',
    'yourPart': 'Sua parte está destacada',
    'preview': 'Pré-visualização',
    'savedToAlbum': '+1 lição! Seu desenho foi salvo em Meu álbum.',
    'sound': 'Som',
    'exitDrawing': 'Sair do desenho',
    'colorMore': 'Pinte mais a área destacada',
    'perfectDrawing': 'Desenho perfeito',
    'greatDrawing': 'Ótimo desenho',
    'goodDrawing': 'Belo desenho',
    'point': 'Pontos',
    'lines': 'Traços',
    'time': 'Tempo',
    'shareShort': 'Compartilhar',
    'drawAgain': 'Desenhar de novo',
    'savedGallery': 'Imagem salva na galeria!',
    'saveFailed': 'Algo deu errado! Tente novamente mais tarde.',
    'tellUsTitle': 'Diga do que você precisa',
    'tellUsSub': 'Conte suas ideias ou problemas',
    'requestFeature': 'Pedir recurso',
    'reportBug': 'Relatar erro',
    'c_character': 'Personagens',
    'c_plant': 'Plantas',
    'justNow': 'agora',
    'minutesAgo': 'há {n} min',
    'hoursAgo': 'há {n} h',
    'daysAgo': 'há {n} d',
    'noBuddiesYet': 'Ainda sem amigos',
    'noBuddiesSub': 'Desenhe com alguém para adicionar seu primeiro amigo',
    'findNewBuddy': 'Encontrar um novo amigo',
    'drewTogether': 'Desenharam juntos',
    'findingBuddies': 'Procurando parceiros de desenho...',
    'readyToDraw': 'Pronto para desenhar!',
    'readyWord': 'prontos',
    'waiting': 'Aguardando...',
    'startingIn': 'Começando em {n}...',
    'drawingPartner': 'Parceiro de desenho',
    'doneWord': 'Pronto',
    'drawingWord': 'Desenhando',
    'premiumSub': 'Amado por jovens artistas',
    'featNoAds': 'Desenho sem anúncios',
    'featNewContent': 'Conteúdo novo toda semana',
    'featSupport': 'Suporte ao cliente',
    'yearly': 'Anual',
    'weekly': 'Semanal',
    'save90': 'Economize 90%',
    'justPerYear': 'Apenas {p}/ano',
    'weekShort': 'semana',
    'processing': 'Processando...',
    'cancelAnytime': 'Cancele quando quiser',
    'subDisclaimer': 'O pagamento começará após o fim do período de teste grátis. Cancele antes do fim do teste para não ser cobrado. A assinatura será renovada automaticamente até você cancelar.',
    'privacy': 'Privacidade',
    'terms': 'Termos',
    'restorePurchase': 'Restaurar compra',
    'nothingToRestore': 'Não há nada para restaurar.',
    'restoreSuccess': 'Seu Premium foi restaurado!',
    'storeUnavailable': 'A loja não está disponível agora. Tente mais tarde.',
    'purchaseFailed': 'A compra falhou. Tente novamente.',
    'welcomePremium': 'Bem-vindo ao Premium! Desenhe sem anúncios.',
    'alreadyPremium': 'Você já tem Premium.',
    'premiumActive': 'Premium ativo ✓',
    'productNotFound': 'As assinaturas ainda não estão configuradas no Google Play.',
    'othersNotFinished': 'Os outros ainda não terminaram',
    'allFinishedTap': 'Todos terminaram! Toque →',
    'youAre1': 'VOCÊ É 1º!',
    'youAre2': 'VOCÊ É 2º!',
    'youAre3': 'VOCÊ É 3º!',
    'youAre4': 'VOCÊ É 4º!',
    'clearStepTitle': 'Limpar esta etapa',
    'clearStepSub': 'Apagar todos os desenhos da tela.',
    'clearWord': 'Limpar',
    'rateForUs': 'Avalie-nos',
    'rateForUsSub': 'Sua avaliação nos ajuda a melhorar as lições',
    'c_popular': 'Popular',
    'c_seasonal': 'Sazonal',
    'randomMatch': 'Partida aleatória',
    'joinRoom': 'Entrar na sala',
    'enterRoomCode': 'Digite o código',
    'roomCodeSub': 'Código de 4 dígitos do seu amigo',
    'pasteClipboard': 'Colar da área de transferência',
    'roomNotFound': 'Sala não encontrada. Confira o código e tente de novo.',
    'inviteFriend': 'Convidar um amigo',
    'roomCodeTitle': 'Código da sala',
    'waitingFriend': 'Esperando seu amigo...',
    'copyCode': 'Copiar',
    'codeCopied': 'Código copiado!',
    'shareCode': 'Desenhe comigo no {app}! Abra Desenhar juntos → Entrar na sala e digite o código {code}',
    'joiningRoom': 'Entrando na sala...',
    'inviteFriendBtn': 'Convidar amigo',
    'createLobby': 'Criar sala',
    'lobby': 'Sala',
    'change': 'Trocar',
    'youHost': 'Você · anfitrião',
    'invite': 'Convidar',
    'roomCodeCaps': 'CÓDIGO DA SALA',
    'roomCodeShare': 'Compartilhe o ID da sala com amigos.',
    'friendNearby': 'Tem um amigo por perto?',
    'sendCode': 'Envie o código da sala',
    'letsDraw': 'Vamos desenhar!',
    'drawMyself': 'Vou desenhar sozinho',
    'slotOpen': '1 vaga ainda aberta',
    'pickHow': 'Escolha como começar.',
    'fillNow': 'Preencher agora',
    'waitFriends': 'Esperar amigos',
    'findingBuddiesTitle': 'Procurando parceiros...',
    'stepsCount': '{n} etapas',
    'notOnCamera': 'Sem câmera',
    'friendStillDrawing': '{n} amigo ainda desenhando',
    'friendDone': 'Seu parceiro terminou!',
    'noMessages': 'Nenhuma mensagem ainda',
    'sayHi': 'Diga oi aos seus parceiros',
    'saySomething': 'Diga algo...',
    'react': 'Reagir',
    'emojiTab': 'Emoji',
    'phraseTab': 'Frase',
    'emojiOnly': 'Só emojis e frases com novos parceiros',
    'choosePicture': 'Escolha um desenho',
    'friendJoined': '{name} entrou!',
    'ph1': 'Oi! 👋',
    'ph2': 'Bom trabalho!',
    'ph3': 'Que fofo!',
    'ph4': 'Vamos lá!',
    'ph5': 'Que cores lindas!',
    'ph6': 'Quase pronto!',
    'ph7': 'Obrigado!',
    'ph8': 'Muito bem! 🎉',
    'onlineNeeded': 'Convidar um amigo precisa de internet.',
  },
  'fr': {
    'loading': 'Chargement',
    'tagline': 'Dessinons ensemble',
    'chooseLanguage': 'Choisissez votre langue',
    'changeAnytime': 'Vous pouvez la modifier à tout moment dans les Paramètres',
    'continue': 'Continuer',
    'ageTitle': 'Dites-nous votre âge',
    'ageSub': 'Pour commencer votre aventure créative !',
    'year': 'ans',
    'purposeTitle': "Qu'est-ce qui vous amène aujourd'hui ?",
    'purposeSub': 'Choisissez celle qui vous correspond le mieux',
    'p_relax': 'Me détendre et réduire le stress',
    'p_connect': "Échanger et dessiner avec d'autres",
    'p_improve': 'Améliorer mes compétences en dessin',
    'p_kids': 'Apprendre à dessiner à mes enfants',
    'p_health': 'Me remettre de problèmes de santé',
    'p_other': 'Autre',
    'interestsTitle': "Dites-nous ce qui vous intéresse",
    'interestsSub': 'Sélectionnez au moins 1 option',
    'i_animal': 'Animaux',
    'i_food': 'Nourriture',
    'i_cartoon': 'Dessin animé',
    'i_anime': 'Anime',
    'i_kpop': 'Idoles K-Pop',
    'i_plant': 'Plantes',
    'i_worldcup': 'Coupe du monde',
    'i_seasonal': 'Saisonnier',
    'goodMorning': 'Bonjour',
    'goodAfternoon': 'Bon après-midi',
    'goodEvening': 'Bonsoir',
    'premium': 'Premium',
    'profile': 'Profil',
    'spentTime': 'Temps passé',
    'lesson': 'Leçon',
    'yourLevel': 'Votre niveau',
    'levels': 'Niveaux',
    'levelDesc': 'Terminez des leçons pour monter de niveau !',
    'lessonsNeeded': '{n} leçons',
    'myBuddies': 'Mes amis',
    'buddiesCount': '{n} amis',
    'noBuddies': "Pas encore d'amis. Dessinez avec d'autres pour vous faire des amis !",
    'myAlbum': 'Mon album',
    'favorite': 'Favoris',
    'sortNewest': 'Plus récents',
    'sortOldest': 'Plus anciens',
    'drawNow': 'Dessiner',
    'setting': 'Paramètres',
    'turnOffMessages': 'Désactiver les messages',
    'music': 'Musique',
    'soundFx': 'Effets sonores',
    'vibrate': 'Vibration',
    'language': 'Langue',
    'share': 'Partager avec vos amis',
    'rate': 'Notez 5 étoiles',
    'feedback': 'Commentaires',
    'policy': 'Politique',
    'checkUpdate': 'Rechercher une mise à jour',
    'rateTitle': 'Aimez-vous cette application ?',
    'rateSub': "Votre note nous aidera à améliorer encore l'application.",
    'rateUs': 'Noter',
    'thanksRating': 'Merci pour votre note !',
    'comingSoon': 'Bientôt disponible !',
    'editName': 'Modifier le nom',
    'chooseAvatar': "Choisir l'avatar",
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'shareText': 'Dessinons ensemble sur {app} ! Téléchargez-la ici : {url}',
    'feedbackSubject': 'Commentaires pour {app}',
    'cantOpen': "Impossible d'ouvrir le lien",
    'lv_novice': 'Novice',
    'lv_apprentice': 'Apprenti',
    'lv_budding': 'En herbe',
    'lv_emerging': 'Émergent',
    'lv_developing': 'En progrès',
    'lv_skilled': 'Habile',
    'lv_proficient': 'Compétent',
    'lv_accomplished': 'Accompli',
    'lv_master': 'Maître',
    'lv_expert': 'Expert',
    'lv_virtuoso': 'Virtuose',
    'lv_legendary': 'Légendaire',
    'unlockHint': 'Terminez {n} leçons pour débloquer',
    'levelUnlocked': 'Débloqué !',
    'drawTogether': 'Dessiner ensemble',
    'quickMatch': 'Partie rapide',
    'randomPlayer': 'Joueur aléatoire',
    'privateMatch': 'Partie privée',
    'withFriends': 'Avec des amis',
    'popular': 'Populaire',
    'draw': 'Dessiner',
    'traceArt': 'Décalquer',
    'c_beginner': 'Débutant',
    'c_trending': 'Tendance',
    'c_neon': 'Néon',
    'c_xmas': 'Noël',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Décalquez d’abord le dessin !',
    'greatJob': 'Bravo !',
    'lessonDone': '+1 leçon terminée. Continuez pour monter de niveau !',
    'selectRoom': 'Choisir une salle',
    'players4': '4 joueurs',
    'players2': '2 joueurs',
    'selectTemplate': 'Choisir un modèle',
    'findingPlayers': 'Recherche d’autres\njoueurs',
    'searching': 'Recherche',
    'matched': 'PARTENAIRES\nTROUVÉS',
    'leaveTitle': 'Voulez-vous quitter ?',
    'stillDrawing': 'CONTINUER À DESSINER',
    'quit': 'Quitter',
    'strokeWrong': 'Vous devez tracer le trait actuel correctement',
    'colorNow': 'Contour terminé ! Coloriez puis touchez →',
    'waitingOthers': 'En attente des autres joueurs...',
    'results': 'Résultats',
    'ourArtwork': 'Notre œuvre',
    'playAgain': 'Rejouer',
    'home': 'Accueil',
    'you': 'Vous',
    'accuracy': 'Précision',
    'leftGame': 'Parti',
    'yourPart': 'Votre partie est en surbrillance',
    'preview': 'Aperçu',
    'savedToAlbum': '+1 leçon ! Votre dessin est enregistré dans Mon album.',
    'sound': 'Son',
    'exitDrawing': 'Quitter le dessin',
    'colorMore': 'Coloriez davantage la zone en surbrillance',
    'perfectDrawing': 'Dessin parfait',
    'greatDrawing': 'Super dessin',
    'goodDrawing': 'Joli dessin',
    'point': 'Points',
    'lines': 'Traits',
    'time': 'Temps',
    'shareShort': 'Partager',
    'drawAgain': 'Redessiner',
    'savedGallery': 'Image enregistrée dans la galerie !',
    'saveFailed': 'Un problème est survenu ! Réessayez plus tard.',
    'tellUsTitle': 'Dites-nous ce dont vous avez besoin',
    'tellUsSub': 'Partagez vos idées ou problèmes',
    'requestFeature': 'Demander une fonction',
    'reportBug': 'Signaler un bug',
    'c_character': 'Personnages',
    'c_plant': 'Plantes',
    'justNow': 'à l’instant',
    'minutesAgo': 'il y a {n} min',
    'hoursAgo': 'il y a {n} h',
    'daysAgo': 'il y a {n} j',
    'noBuddiesYet': 'Pas encore d’amis',
    'noBuddiesSub': 'Dessinez avec quelqu’un pour ajouter votre premier ami',
    'findNewBuddy': 'Trouver un nouvel ami',
    'drewTogether': 'Dessiné ensemble',
    'findingBuddies': 'Recherche de partenaires...',
    'readyToDraw': 'Prêts à dessiner !',
    'readyWord': 'prêts',
    'waiting': 'En attente...',
    'startingIn': 'Début dans {n}...',
    'drawingPartner': 'Partenaire de dessin',
    'doneWord': 'Terminé',
    'drawingWord': 'En train de dessiner',
    'premiumSub': 'Adoré des jeunes artistes',
    'featNoAds': 'Dessin sans publicité',
    'featNewContent': 'Nouveau contenu chaque semaine',
    'featSupport': 'Service client',
    'yearly': 'Annuel',
    'weekly': 'Hebdomadaire',
    'save90': 'Économisez 90%',
    'justPerYear': 'Seulement {p}/an',
    'weekShort': 'semaine',
    'processing': 'Traitement...',
    'cancelAnytime': 'Annulez à tout moment',
    'subDisclaimer': 'Le paiement commencera à la fin de l’essai gratuit. Annulez avant la fin de l’essai pour ne pas être facturé. L’abonnement se renouvelle automatiquement jusqu’à annulation.',
    'privacy': 'Confidentialité',
    'terms': 'Conditions',
    'restorePurchase': 'Restaurer l’achat',
    'nothingToRestore': 'Rien à restaurer.',
    'restoreSuccess': 'Votre Premium a été restauré !',
    'storeUnavailable': 'La boutique est indisponible. Réessayez plus tard.',
    'purchaseFailed': 'Échec de l’achat. Réessayez.',
    'welcomePremium': 'Bienvenue dans Premium ! Dessinez sans publicité.',
    'alreadyPremium': 'Vous avez déjà Premium.',
    'premiumActive': 'Premium actif ✓',
    'productNotFound': 'Les abonnements ne sont pas encore configurés dans Google Play.',
    'othersNotFinished': 'Les autres n\'ont pas fini',
    'allFinishedTap': 'Tout le monde a fini ! Touche →',
    'youAre1': 'TU ES 1er !',
    'youAre2': 'TU ES 2e !',
    'youAre3': 'TU ES 3e !',
    'youAre4': 'TU ES 4e !',
    'clearStepTitle': 'Effacer cette étape',
    'clearStepSub': 'Supprimer tous les dessins de la toile.',
    'clearWord': 'Effacer',
    'rateForUs': 'Notez-nous',
    'rateForUsSub': 'Votre note nous aide à améliorer nos leçons',
    'c_popular': 'Populaire',
    'c_seasonal': 'Saison',
    'randomMatch': 'Partie aléatoire',
    'joinRoom': 'Rejoindre',
    'enterRoomCode': 'Entre le code',
    'roomCodeSub': 'Code à 4 chiffres de ton ami',
    'pasteClipboard': 'Coller depuis le presse-papiers',
    'roomNotFound': 'Salle introuvable. Vérifie le code et réessaie.',
    'inviteFriend': 'Inviter un ami',
    'roomCodeTitle': 'Code de salle',
    'waitingFriend': 'En attente de ton ami...',
    'copyCode': 'Copier',
    'codeCopied': 'Code copié !',
    'shareCode': 'Dessine avec moi sur {app} ! Ouvre Dessiner ensemble → Rejoindre et entre le code {code}',
    'joiningRoom': 'Connexion à la salle...',
    'inviteFriendBtn': 'Inviter un ami',
    'createLobby': 'Créer un salon',
    'lobby': 'Salon',
    'change': 'Changer',
    'youHost': 'Toi · hôte',
    'invite': 'Inviter',
    'roomCodeCaps': 'CODE DU SALON',
    'roomCodeShare': 'Partage l\'ID du salon avec tes amis.',
    'friendNearby': 'Un ami à côté ?',
    'sendCode': 'Envoie-lui le code du salon',
    'letsDraw': 'On dessine !',
    'drawMyself': 'Je dessine seul',
    'slotOpen': '1 place encore libre',
    'pickHow': 'Choisis comment commencer.',
    'fillNow': 'Compléter maintenant',
    'waitFriends': 'Attendre des amis',
    'findingBuddiesTitle': 'Recherche de copains...',
    'stepsCount': '{n} étapes',
    'notOnCamera': 'Caméra coupée',
    'friendStillDrawing': '{n} ami dessine encore',
    'friendDone': 'Ton copain a fini !',
    'noMessages': 'Pas encore de messages',
    'sayHi': 'Dis bonjour à tes copains',
    'saySomething': 'Dis quelque chose...',
    'react': 'Réagir',
    'emojiTab': 'Emoji',
    'phraseTab': 'Phrase',
    'emojiOnly': 'Emojis et phrases seulement avec les nouveaux copains',
    'choosePicture': 'Choisis un dessin',
    'friendJoined': '{name} a rejoint !',
    'ph1': 'Salut ! 👋',
    'ph2': 'Bravo !',
    'ph3': 'Trop mignon !',
    'ph4': 'Allons-y !',
    'ph5': 'Belles couleurs !',
    'ph6': 'Presque fini !',
    'ph7': 'Merci !',
    'ph8': 'Bien joué ! 🎉',
    'onlineNeeded': 'Inviter un ami nécessite Internet.',
  },
  'de': {
    'loading': 'Lädt',
    'tagline': 'Zusammen zeichnen',
    'chooseLanguage': 'Wähle deine Sprache',
    'changeAnytime': 'Du kannst das jederzeit in den Einstellungen ändern',
    'continue': 'Weiter',
    'ageTitle': 'Wie alt bist du?',
    'ageSub': 'Um deine kreative Reise zu beginnen!',
    'year': 'Jahre',
    'purposeTitle': 'Was führt dich heute her?',
    'purposeSub': 'Wähle, was am besten zu dir passt',
    'p_relax': 'Entspannen und Stress abbauen',
    'p_connect': 'Mit anderen zeichnen',
    'p_improve': 'Meine Zeichenfähigkeiten verbessern',
    'p_kids': 'Meinen Kindern Zeichnen beibringen',
    'p_health': 'Mich von Krankheit erholen',
    'p_other': 'Sonstiges',
    'interestsTitle': 'Was interessiert dich?',
    'interestsSub': 'Wähle mindestens 1 Option',
    'i_animal': 'Tiere',
    'i_food': 'Essen',
    'i_cartoon': 'Cartoon',
    'i_anime': 'Anime',
    'i_kpop': 'K-Pop-Idole',
    'i_plant': 'Pflanzen',
    'i_worldcup': 'Weltmeisterschaft',
    'i_seasonal': 'Saisonal',
    'goodMorning': 'Guten Morgen',
    'goodAfternoon': 'Guten Tag',
    'goodEvening': 'Guten Abend',
    'premium': 'Premium',
    'profile': 'Profil',
    'spentTime': 'Verbrachte Zeit',
    'lesson': 'Lektion',
    'yourLevel': 'Dein Level',
    'levels': 'Level',
    'levelDesc': 'Schließe Lektionen ab, um aufzusteigen!',
    'lessonsNeeded': '{n} Lektionen',
    'myBuddies': 'Meine Freunde',
    'buddiesCount': '{n} Freunde',
    'noBuddies': 'Noch keine Freunde. Zeichne mit anderen, um Freunde zu finden!',
    'myAlbum': 'Mein Album',
    'favorite': 'Favoriten',
    'sortNewest': 'Neueste zuerst',
    'sortOldest': 'Älteste zuerst',
    'drawNow': 'Jetzt zeichnen',
    'setting': 'Einstellungen',
    'turnOffMessages': 'Nachrichten ausschalten',
    'music': 'Musik',
    'soundFx': 'Soundeffekte',
    'vibrate': 'Vibration',
    'language': 'Sprache',
    'share': 'Mit Freunden teilen',
    'rate': 'Mit 5 Sternen bewerten',
    'feedback': 'Feedback',
    'policy': 'Datenschutz',
    'checkUpdate': 'Nach Updates suchen',
    'rateTitle': 'Gefällt dir diese App?',
    'rateSub': 'Deine Bewertung hilft uns, die App noch besser zu machen.',
    'rateUs': 'Bewerten',
    'thanksRating': 'Danke für deine Bewertung!',
    'comingSoon': 'Demnächst verfügbar!',
    'editName': 'Namen ändern',
    'chooseAvatar': 'Avatar wählen',
    'save': 'Speichern',
    'cancel': 'Abbrechen',
    'shareText': 'Lass uns zusammen in {app} zeichnen! Hier herunterladen: {url}',
    'feedbackSubject': 'Feedback zu {app}',
    'cantOpen': 'Link konnte nicht geöffnet werden',
    'lv_novice': 'Anfänger',
    'lv_apprentice': 'Lehrling',
    'lv_budding': 'Knospe',
    'lv_emerging': 'Aufsteiger',
    'lv_developing': 'Fortgeschritten',
    'lv_skilled': 'Geschickt',
    'lv_proficient': 'Versiert',
    'lv_accomplished': 'Vollendet',
    'lv_master': 'Meister',
    'lv_expert': 'Experte',
    'lv_virtuoso': 'Virtuose',
    'lv_legendary': 'Legendär',
    'unlockHint': 'Schließe {n} Lektionen ab, um freizuschalten',
    'levelUnlocked': 'Freigeschaltet!',
    'drawTogether': 'Zusammen zeichnen',
    'quickMatch': 'Schnelles Spiel',
    'randomPlayer': 'Zufälliger Spieler',
    'privateMatch': 'Privates Spiel',
    'withFriends': 'Mit Freunden',
    'popular': 'Beliebt',
    'draw': 'Zeichnen',
    'traceArt': 'Nachzeichnen',
    'c_beginner': 'Anfänger',
    'c_trending': 'Im Trend',
    'c_neon': 'Neon',
    'c_xmas': 'Weihnachten',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Zeichne zuerst das Bild nach!',
    'greatJob': 'Super gemacht!',
    'lessonDone': '+1 Lektion geschafft. Zeichne weiter, um aufzusteigen!',
    'selectRoom': 'Raum wählen',
    'players4': '4 Spieler',
    'players2': '2 Spieler',
    'selectTemplate': 'Vorlage wählen',
    'findingPlayers': 'Suche nach anderen\nSpielern',
    'searching': 'Suche',
    'matched': 'SPIEL\nGEFUNDEN',
    'leaveTitle': 'Möchtest du gehen?',
    'stillDrawing': 'WEITER ZEICHNEN',
    'quit': 'Beenden',
    'strokeWrong': 'Du musst den aktuellen Strich richtig zeichnen',
    'colorNow': 'Umriss fertig! Male ihn aus und tippe auf →',
    'waitingOthers': 'Warte auf andere Spieler...',
    'results': 'Ergebnisse',
    'ourArtwork': 'Unser Kunstwerk',
    'playAgain': 'Nochmal spielen',
    'home': 'Start',
    'you': 'Du',
    'accuracy': 'Genauigkeit',
    'leftGame': 'Verlassen',
    'yourPart': 'Dein Teil ist markiert',
    'preview': 'Vorschau',
    'savedToAlbum': '+1 Lektion! Deine Zeichnung ist in Mein Album gespeichert.',
    'sound': 'Ton',
    'exitDrawing': 'Zeichnen beenden',
    'colorMore': 'Male den markierten Bereich weiter aus',
    'perfectDrawing': 'Perfekte Zeichnung',
    'greatDrawing': 'Tolle Zeichnung',
    'goodDrawing': 'Schöne Zeichnung',
    'point': 'Punkte',
    'lines': 'Linien',
    'time': 'Zeit',
    'shareShort': 'Teilen',
    'drawAgain': 'Nochmal zeichnen',
    'savedGallery': 'Bild in der Galerie gespeichert!',
    'saveFailed': 'Etwas ist schiefgelaufen! Bitte später erneut versuchen.',
    'tellUsTitle': 'Sag uns, was du brauchst',
    'tellUsSub': 'Teile uns Ideen oder Probleme mit',
    'requestFeature': 'Funktion wünschen',
    'reportBug': 'Fehler melden',
    'c_character': 'Figuren',
    'c_plant': 'Pflanzen',
    'justNow': 'gerade eben',
    'minutesAgo': 'vor {n} Min.',
    'hoursAgo': 'vor {n} Std.',
    'daysAgo': 'vor {n} T.',
    'noBuddiesYet': 'Noch keine Freunde',
    'noBuddiesSub': 'Zeichne mit jemandem, um deinen ersten Freund hinzuzufügen',
    'findNewBuddy': 'Neuen Freund finden',
    'drewTogether': 'Zusammen gezeichnet',
    'findingBuddies': 'Suche Zeichenpartner...',
    'readyToDraw': 'Bereit zum Zeichnen!',
    'readyWord': 'bereit',
    'waiting': 'Warte...',
    'startingIn': 'Start in {n}...',
    'drawingPartner': 'Zeichenpartner',
    'doneWord': 'Fertig',
    'drawingWord': 'Zeichnet',
    'premiumSub': 'Beliebt bei jungen Künstlern',
    'featNoAds': 'Zeichnen ohne Werbung',
    'featNewContent': 'Jede Woche neue Inhalte',
    'featSupport': 'Kundensupport',
    'yearly': 'Jährlich',
    'weekly': 'Wöchentlich',
    'save90': 'Spare 90%',
    'justPerYear': 'Nur {p}/Jahr',
    'weekShort': 'Woche',
    'processing': 'Wird bearbeitet...',
    'cancelAnytime': 'Jederzeit kündbar',
    'subDisclaimer': 'Die Zahlung beginnt nach Ende der kostenlosen Testphase. Kündige vor Ende der Testphase, um keine Kosten zu haben. Das Abo verlängert sich automatisch, bis du kündigst.',
    'privacy': 'Datenschutz',
    'terms': 'Bedingungen',
    'restorePurchase': 'Kauf wiederherstellen',
    'nothingToRestore': 'Es gibt nichts wiederherzustellen.',
    'restoreSuccess': 'Dein Premium wurde wiederhergestellt!',
    'storeUnavailable': 'Der Store ist gerade nicht verfügbar. Bitte später erneut versuchen.',
    'purchaseFailed': 'Kauf fehlgeschlagen. Bitte erneut versuchen.',
    'welcomePremium': 'Willkommen bei Premium! Zeichne ohne Werbung.',
    'alreadyPremium': 'Du hast bereits Premium.',
    'premiumActive': 'Premium aktiv ✓',
    'productNotFound': 'Abos sind in Google Play noch nicht eingerichtet.',
    'othersNotFinished': 'Die anderen sind noch nicht fertig',
    'allFinishedTap': 'Alle sind fertig! Tippe →',
    'youAre1': 'DU BIST 1.!',
    'youAre2': 'DU BIST 2.!',
    'youAre3': 'DU BIST 3.!',
    'youAre4': 'DU BIST 4.!',
    'clearStepTitle': 'Diesen Schritt löschen',
    'clearStepSub': 'Alle Zeichnungen auf der Fläche löschen.',
    'clearWord': 'Löschen',
    'rateForUs': 'Bewerte uns',
    'rateForUsSub': 'Deine Bewertung hilft uns, die Lektionen zu verbessern',
    'c_popular': 'Beliebt',
    'c_seasonal': 'Saison',
    'randomMatch': 'Zufälliges Spiel',
    'joinRoom': 'Raum beitreten',
    'enterRoomCode': 'Raumcode eingeben',
    'roomCodeSub': '4-stelliger Code von deinem Freund',
    'pasteClipboard': 'Aus Zwischenablage einfügen',
    'roomNotFound': 'Raum nicht gefunden. Prüfe den Code und versuche es erneut.',
    'inviteFriend': 'Freund einladen',
    'roomCodeTitle': 'Raumcode',
    'waitingFriend': 'Warte auf deinen Freund...',
    'copyCode': 'Kopieren',
    'codeCopied': 'Code kopiert!',
    'shareCode': 'Mal mit mir in {app}! Öffne Zusammen malen → Raum beitreten und gib den Code {code} ein',
    'joiningRoom': 'Raum wird betreten...',
    'inviteFriendBtn': 'Freund einladen',
    'createLobby': 'Lobby erstellen',
    'lobby': 'Lobby',
    'change': 'Ändern',
    'youHost': 'Du · Gastgeber',
    'invite': 'Einladen',
    'roomCodeCaps': 'RAUMCODE',
    'roomCodeShare': 'Teile die Raum-ID mit Freunden.',
    'friendNearby': 'Ein Freund in der Nähe?',
    'sendCode': 'Schick ihm den Raumcode',
    'letsDraw': 'Los geht’s!',
    'drawMyself': 'Ich male allein',
    'slotOpen': '1 Platz noch frei',
    'pickHow': 'Wähle, wie es losgeht.',
    'fillNow': 'Jetzt auffüllen',
    'waitFriends': 'Auf Freunde warten',
    'findingBuddiesTitle': 'Suche Malfreunde...',
    'stepsCount': '{n} Schritte',
    'notOnCamera': 'Kamera aus',
    'friendStillDrawing': '{n} Freund malt noch',
    'friendDone': 'Dein Malfreund ist fertig!',
    'noMessages': 'Noch keine Nachrichten',
    'sayHi': 'Sag Hallo zu deinen Malfreunden',
    'saySomething': 'Sag etwas...',
    'react': 'Reagieren',
    'emojiTab': 'Emoji',
    'phraseTab': 'Satz',
    'emojiOnly': 'Nur Emojis und Sätze mit neuen Malfreunden',
    'choosePicture': 'Bild wählen',
    'friendJoined': '{name} ist da!',
    'ph1': 'Hallo! 👋',
    'ph2': 'Gut gemacht!',
    'ph3': 'So süß!',
    'ph4': 'Los geht’s!',
    'ph5': 'Tolle Farben!',
    'ph6': 'Fast fertig!',
    'ph7': 'Danke!',
    'ph8': 'Super! 🎉',
    'onlineNeeded': 'Zum Einladen brauchst du Internet.',
  },
  'vi': {
    'loading': 'Đang tải',
    'tagline': 'Cùng nhau vẽ',
    'chooseLanguage': 'Chọn ngôn ngữ của bạn',
    'changeAnytime': 'Bạn có thể thay đổi bất cứ lúc nào trong Cài đặt',
    'continue': 'Tiếp tục',
    'ageTitle': 'Cho chúng tôi biết tuổi của bạn',
    'ageSub': 'Để bắt đầu hành trình sáng tạo!',
    'year': 'tuổi',
    'purposeTitle': 'Điều gì đưa bạn đến đây hôm nay?',
    'purposeSub': 'Chọn điều phù hợp nhất với bạn',
    'p_relax': 'Thư giãn và giảm căng thẳng',
    'p_connect': 'Kết nối và vẽ cùng người khác',
    'p_improve': 'Nâng cao kỹ năng vẽ',
    'p_kids': 'Dạy con tôi vẽ',
    'p_health': 'Phục hồi sức khỏe',
    'p_other': 'Khác',
    'interestsTitle': 'Cho chúng tôi biết sở thích của bạn',
    'interestsSub': 'Chọn ít nhất 1 mục',
    'i_animal': 'Động vật',
    'i_food': 'Đồ ăn',
    'i_cartoon': 'Hoạt hình',
    'i_anime': 'Anime',
    'i_kpop': 'Thần tượng K-Pop',
    'i_plant': 'Cây cối',
    'i_worldcup': 'World Cup',
    'i_seasonal': 'Theo mùa',
    'goodMorning': 'Chào buổi sáng',
    'goodAfternoon': 'Chào buổi chiều',
    'goodEvening': 'Chào buổi tối',
    'premium': 'Premium',
    'profile': 'Hồ sơ',
    'spentTime': 'Thời gian',
    'lesson': 'Bài học',
    'yourLevel': 'Cấp độ',
    'levels': 'Cấp độ',
    'levelDesc': 'Hoàn thành bài học để lên cấp!',
    'lessonsNeeded': '{n} bài học',
    'myBuddies': 'Bạn bè',
    'buddiesCount': '{n} bạn',
    'noBuddies': 'Chưa có bạn bè. Hãy vẽ cùng mọi người để kết bạn!',
    'myAlbum': 'Album của tôi',
    'favorite': 'Yêu thích',
    'sortNewest': 'Mới nhất',
    'sortOldest': 'Cũ nhất',
    'drawNow': 'Vẽ ngay',
    'setting': 'Cài đặt',
    'turnOffMessages': 'Tắt tin nhắn',
    'music': 'Nhạc',
    'soundFx': 'Hiệu ứng âm thanh',
    'vibrate': 'Rung',
    'language': 'Ngôn ngữ',
    'share': 'Chia sẻ với bạn bè',
    'rate': 'Đánh giá 5 sao',
    'feedback': 'Góp ý',
    'policy': 'Chính sách',
    'checkUpdate': 'Kiểm tra cập nhật',
    'rateTitle': 'Bạn có thích ứng dụng này không?',
    'rateSub': 'Đánh giá của bạn giúp chúng tôi cải thiện ứng dụng tốt hơn.',
    'rateUs': 'Đánh giá',
    'thanksRating': 'Cảm ơn bạn đã đánh giá!',
    'comingSoon': 'Sắp ra mắt!',
    'editName': 'Sửa tên',
    'chooseAvatar': 'Chọn ảnh đại diện',
    'save': 'Lưu',
    'cancel': 'Hủy',
    'shareText': 'Cùng vẽ trên {app} nhé! Tải tại đây: {url}',
    'feedbackSubject': 'Góp ý cho {app}',
    'cantOpen': 'Không thể mở liên kết',
    'lv_novice': 'Người mới',
    'lv_apprentice': 'Học việc',
    'lv_budding': 'Chớm nở',
    'lv_emerging': 'Triển vọng',
    'lv_developing': 'Đang phát triển',
    'lv_skilled': 'Thành thạo',
    'lv_proficient': 'Tinh thông',
    'lv_accomplished': 'Xuất sắc',
    'lv_master': 'Bậc thầy',
    'lv_expert': 'Chuyên gia',
    'lv_virtuoso': 'Điêu luyện',
    'lv_legendary': 'Huyền thoại',
    'unlockHint': 'Hoàn thành {n} bài học để mở khóa',
    'levelUnlocked': 'Đã mở khóa!',
    'drawTogether': 'Vẽ cùng nhau',
    'quickMatch': 'Trận nhanh',
    'randomPlayer': 'Người chơi ngẫu nhiên',
    'privateMatch': 'Trận riêng',
    'withFriends': 'Với bạn bè',
    'popular': 'Phổ biến',
    'draw': 'Vẽ',
    'traceArt': 'Vẽ theo mẫu',
    'c_beginner': 'Cơ bản',
    'c_trending': 'Thịnh hành',
    'c_neon': 'Neon',
    'c_xmas': 'Giáng sinh',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Hãy vẽ theo hình trước!',
    'greatJob': 'Tuyệt vời!',
    'lessonDone': '+1 bài học hoàn thành. Tiếp tục vẽ để lên cấp!',
    'selectRoom': 'Chọn phòng',
    'players4': '4 người chơi',
    'players2': '2 người chơi',
    'selectTemplate': 'Chọn mẫu',
    'findingPlayers': 'Đang tìm người\nchơi khác',
    'searching': 'Đang tìm',
    'matched': 'ĐÃ GHÉP\nĐÔI!',
    'leaveTitle': 'Bạn có muốn rời đi?',
    'stillDrawing': 'TIẾP TỤC VẼ',
    'quit': 'Thoát',
    'strokeWrong': 'Bạn cần vẽ đúng nét hiện tại',
    'colorNow': 'Xong nét viền! Tô màu rồi nhấn →',
    'waitingOthers': 'Đang chờ người chơi khác...',
    'results': 'Kết quả',
    'ourArtwork': 'Tác phẩm chung',
    'playAgain': 'Chơi lại',
    'home': 'Trang chủ',
    'you': 'Bạn',
    'accuracy': 'Độ chính xác',
    'leftGame': 'Đã rời',
    'yourPart': 'Phần của bạn được làm nổi bật',
    'preview': 'Xem trước',
    'savedToAlbum': '+1 bài học! Bức vẽ đã được lưu vào Album của tôi.',
    'sound': 'Âm thanh',
    'exitDrawing': 'Thoát vẽ',
    'colorMore': 'Tô thêm vùng được đánh dấu',
    'perfectDrawing': 'Bức vẽ hoàn hảo',
    'greatDrawing': 'Bức vẽ tuyệt vời',
    'goodDrawing': 'Bức vẽ đẹp',
    'point': 'Điểm',
    'lines': 'Nét',
    'time': 'Thời gian',
    'shareShort': 'Chia sẻ',
    'drawAgain': 'Vẽ lại',
    'savedGallery': 'Đã lưu ảnh vào thư viện!',
    'saveFailed': 'Đã xảy ra lỗi! Vui lòng thử lại sau.',
    'tellUsTitle': 'Cho chúng tôi biết bạn cần gì',
    'tellUsSub': 'Chia sẻ ý tưởng hoặc sự cố',
    'requestFeature': 'Đề xuất tính năng',
    'reportBug': 'Báo lỗi',
    'c_character': 'Nhân vật',
    'c_plant': 'Cây cối',
    'justNow': 'vừa xong',
    'minutesAgo': '{n} phút trước',
    'hoursAgo': '{n} giờ trước',
    'daysAgo': '{n} ngày trước',
    'noBuddiesYet': 'Chưa có bạn vẽ',
    'noBuddiesSub': 'Vẽ cùng ai đó để thêm người bạn đầu tiên',
    'findNewBuddy': 'Tìm bạn vẽ mới',
    'drewTogether': 'Đã vẽ cùng nhau',
    'findingBuddies': 'Đang tìm bạn vẽ...',
    'readyToDraw': 'Sẵn sàng vẽ!',
    'readyWord': 'sẵn sàng',
    'waiting': 'Đang chờ...',
    'startingIn': 'Bắt đầu sau {n}...',
    'drawingPartner': 'Bạn vẽ cùng',
    'doneWord': 'Xong',
    'drawingWord': 'Đang vẽ',
    'premiumSub': 'Được các họa sĩ nhí yêu thích',
    'featNoAds': 'Vẽ không quảng cáo',
    'featNewContent': 'Nội dung mới mỗi tuần',
    'featSupport': 'Hỗ trợ khách hàng',
    'yearly': 'Hằng năm',
    'weekly': 'Hằng tuần',
    'save90': 'Tiết kiệm 90%',
    'justPerYear': 'Chỉ {p}/năm',
    'weekShort': 'tuần',
    'processing': 'Đang xử lý...',
    'cancelAnytime': 'Hủy bất cứ lúc nào',
    'subDisclaimer': 'Thanh toán bắt đầu sau khi hết thời gian dùng thử miễn phí. Hủy trước khi hết thời gian dùng thử để không bị tính phí. Gói đăng ký tự động gia hạn cho đến khi bạn hủy.',
    'privacy': 'Quyền riêng tư',
    'terms': 'Điều khoản',
    'restorePurchase': 'Khôi phục giao dịch',
    'nothingToRestore': 'Không có gì để khôi phục.',
    'restoreSuccess': 'Premium của bạn đã được khôi phục!',
    'storeUnavailable': 'Cửa hàng hiện không khả dụng. Vui lòng thử lại sau.',
    'purchaseFailed': 'Mua thất bại. Vui lòng thử lại.',
    'welcomePremium': 'Chào mừng đến với Premium! Vẽ không quảng cáo.',
    'alreadyPremium': 'Bạn đã có Premium.',
    'premiumActive': 'Premium đang hoạt động ✓',
    'productNotFound': 'Gói đăng ký chưa được thiết lập trên Google Play.',
    'othersNotFinished': 'Người chơi khác chưa xong',
    'allFinishedTap': 'Mọi người đã xong! Nhấn →',
    'youAre1': 'BẠN HẠNG 1!',
    'youAre2': 'BẠN HẠNG 2!',
    'youAre3': 'BẠN HẠNG 3!',
    'youAre4': 'BẠN HẠNG 4!',
    'clearStepTitle': 'Xóa bước này',
    'clearStepSub': 'Xóa tất cả nét vẽ trên bảng vẽ.',
    'clearWord': 'Xóa',
    'rateForUs': 'Đánh giá chúng tôi',
    'rateForUsSub': 'Đánh giá của bạn giúp chúng tôi cải thiện bài học',
    'c_popular': 'Phổ biến',
    'c_seasonal': 'Theo mùa',
    'randomMatch': 'Ghép ngẫu nhiên',
    'joinRoom': 'Vào phòng',
    'enterRoomCode': 'Nhập mã phòng',
    'roomCodeSub': 'Mã 4 số từ bạn của bạn',
    'pasteClipboard': 'Dán từ bộ nhớ tạm',
    'roomNotFound': 'Không tìm thấy phòng. Kiểm tra mã và thử lại.',
    'inviteFriend': 'Mời bạn bè',
    'roomCodeTitle': 'Mã phòng',
    'waitingFriend': 'Đang chờ bạn của bạn...',
    'copyCode': 'Sao chép',
    'codeCopied': 'Đã sao chép mã!',
    'shareCode': 'Vẽ cùng mình trên {app}! Mở Vẽ cùng nhau → Vào phòng và nhập mã {code}',
    'joiningRoom': 'Đang vào phòng...',
    'inviteFriendBtn': 'Mời bạn',
    'createLobby': 'Tạo phòng',
    'lobby': 'Phòng chờ',
    'change': 'Đổi',
    'youHost': 'Bạn · chủ phòng',
    'invite': 'Mời',
    'roomCodeCaps': 'MÃ PHÒNG',
    'roomCodeShare': 'Chia sẻ mã phòng chờ với bạn bè.',
    'friendNearby': 'Có bạn ở gần không?',
    'sendCode': 'Gửi mã phòng cho bạn ấy',
    'letsDraw': 'Vẽ thôi!',
    'drawMyself': 'Mình sẽ vẽ một mình',
    'slotOpen': 'Còn 1 chỗ trống',
    'pickHow': 'Chọn cách bắt đầu.',
    'fillNow': 'Ghép ngay',
    'waitFriends': 'Chờ bạn bè',
    'findingBuddiesTitle': 'Đang tìm bạn vẽ...',
    'stepsCount': '{n} bước',
    'notOnCamera': 'Không bật camera',
    'friendStillDrawing': '{n} bạn vẫn đang vẽ',
    'friendDone': 'Bạn vẽ đã xong!',
    'noMessages': 'Chưa có tin nhắn',
    'sayHi': 'Chào bạn vẽ của bạn nhé',
    'saySomething': 'Nói gì đó...',
    'react': 'Thả cảm xúc',
    'emojiTab': 'Emoji',
    'phraseTab': 'Câu',
    'emojiOnly': 'Chỉ emoji và câu có sẵn với bạn mới',
    'choosePicture': 'Chọn tranh',
    'friendJoined': '{name} đã vào!',
    'ph1': 'Chào! 👋',
    'ph2': 'Giỏi lắm!',
    'ph3': 'Dễ thương quá!',
    'ph4': 'Bắt đầu nào!',
    'ph5': 'Màu đẹp quá!',
    'ph6': 'Sắp xong rồi!',
    'ph7': 'Cảm ơn!',
    'ph8': 'Tuyệt vời! 🎉',
    'onlineNeeded': 'Mời bạn cần có kết nối mạng.',
  },
  'id': {
    'loading': 'Memuat',
    'tagline': 'Menggambar bersama',
    'chooseLanguage': 'Pilih bahasamu',
    'changeAnytime': 'Kamu bisa mengubahnya kapan saja di Pengaturan',
    'continue': 'Lanjut',
    'ageTitle': 'Beri tahu kami usiamu',
    'ageSub': 'Untuk memulai perjalanan kreatifmu!',
    'year': 'tahun',
    'purposeTitle': 'Jadi, apa yang membawamu ke sini?',
    'purposeSub': 'Pilih yang paling sesuai denganmu',
    'p_relax': 'Bersantai dan mengurangi stres',
    'p_connect': 'Terhubung dan menggambar bersama',
    'p_improve': 'Meningkatkan kemampuan menggambar',
    'p_kids': 'Mengajari anak menggambar',
    'p_health': 'Pemulihan dari masalah kesehatan',
    'p_other': 'Lainnya',
    'interestsTitle': 'Beri tahu kami minatmu',
    'interestsSub': 'Pilih minimal 1 opsi',
    'i_animal': 'Hewan',
    'i_food': 'Makanan',
    'i_cartoon': 'Kartun',
    'i_anime': 'Anime',
    'i_kpop': 'Idola K-Pop',
    'i_plant': 'Tanaman',
    'i_worldcup': 'Piala Dunia',
    'i_seasonal': 'Musiman',
    'goodMorning': 'Selamat pagi',
    'goodAfternoon': 'Selamat siang',
    'goodEvening': 'Selamat malam',
    'premium': 'Premium',
    'profile': 'Profil',
    'spentTime': 'Waktu',
    'lesson': 'Pelajaran',
    'yourLevel': 'Levelmu',
    'levels': 'Level',
    'levelDesc': 'Selesaikan pelajaran untuk naik level!',
    'lessonsNeeded': '{n} pelajaran',
    'myBuddies': 'Temanku',
    'buddiesCount': '{n} teman',
    'noBuddies': 'Belum ada teman. Menggambarlah bersama untuk berteman!',
    'myAlbum': 'Albumku',
    'favorite': 'Favorit',
    'sortNewest': 'Terbaru',
    'sortOldest': 'Terlama',
    'drawNow': 'Gambar',
    'setting': 'Pengaturan',
    'turnOffMessages': 'Matikan pesan',
    'music': 'Musik',
    'soundFx': 'Efek suara',
    'vibrate': 'Getar',
    'language': 'Bahasa',
    'share': 'Bagikan ke teman',
    'rate': 'Beri 5 bintang',
    'feedback': 'Masukan',
    'policy': 'Kebijakan',
    'checkUpdate': 'Periksa pembaruan',
    'rateTitle': 'Apakah kamu suka aplikasi ini?',
    'rateSub': 'Penilaianmu membantu kami membuat aplikasi lebih baik.',
    'rateUs': 'Beri Nilai',
    'thanksRating': 'Terima kasih atas penilaianmu!',
    'comingSoon': 'Segera hadir!',
    'editName': 'Ubah nama',
    'chooseAvatar': 'Pilih avatar',
    'save': 'Simpan',
    'cancel': 'Batal',
    'shareText': 'Ayo menggambar bersama di {app}! Unduh di sini: {url}',
    'feedbackSubject': 'Masukan untuk {app}',
    'cantOpen': 'Tidak dapat membuka tautan',
    'lv_novice': 'Pemula',
    'lv_apprentice': 'Magang',
    'lv_budding': 'Bertunas',
    'lv_emerging': 'Berkembang',
    'lv_developing': 'Maju',
    'lv_skilled': 'Terampil',
    'lv_proficient': 'Mahir',
    'lv_accomplished': 'Ulung',
    'lv_master': 'Master',
    'lv_expert': 'Ahli',
    'lv_virtuoso': 'Virtuoso',
    'lv_legendary': 'Legendaris',
    'unlockHint': 'Selesaikan {n} pelajaran untuk membuka',
    'levelUnlocked': 'Terbuka!',
    'drawTogether': 'Gambar Bersama',
    'quickMatch': 'Main Cepat',
    'randomPlayer': 'Pemain Acak',
    'privateMatch': 'Main Privat',
    'withFriends': 'Dengan Teman',
    'popular': 'Populer',
    'draw': 'Gambar',
    'traceArt': 'Jiplak Seni',
    'c_beginner': 'Pemula',
    'c_trending': 'Trending',
    'c_neon': 'Neon',
    'c_xmas': 'Natal',
    'c_halloween': 'Halloween',
    'emptyDrawing': 'Jiplak gambarnya dulu!',
    'greatJob': 'Kerja bagus!',
    'lessonDone': '+1 pelajaran selesai. Terus menggambar untuk naik level!',
    'selectRoom': 'Pilih Ruang',
    'players4': '4 Pemain',
    'players2': '2 Pemain',
    'selectTemplate': 'Pilih Templat',
    'findingPlayers': 'Mencari Pemain\nLain',
    'searching': 'Mencari',
    'matched': 'KAMU SUDAH\nDAPAT LAWAN',
    'leaveTitle': 'Apakah kamu ingin keluar?',
    'stillDrawing': 'LANJUT MENGGAMBAR',
    'quit': 'Keluar',
    'strokeWrong': 'Kamu harus menggambar garis ini dengan benar',
    'colorNow': 'Garis selesai! Warnai lalu ketuk →',
    'waitingOthers': 'Menunggu pemain lain...',
    'results': 'Hasil',
    'ourArtwork': 'Karya kita',
    'playAgain': 'Main Lagi',
    'home': 'Beranda',
    'you': 'Kamu',
    'accuracy': 'Akurasi',
    'leftGame': 'Keluar',
    'yourPart': 'Bagianmu disorot',
    'preview': 'Pratinjau',
    'savedToAlbum': '+1 pelajaran! Gambarmu tersimpan di Albumku.',
    'sound': 'Suara',
    'exitDrawing': 'Keluar Menggambar',
    'colorMore': 'Warnai lebih banyak area yang disorot',
    'perfectDrawing': 'Gambar Sempurna',
    'greatDrawing': 'Gambar Hebat',
    'goodDrawing': 'Gambar Bagus',
    'point': 'Poin',
    'lines': 'Garis',
    'time': 'Waktu',
    'shareShort': 'Bagikan',
    'drawAgain': 'Gambar Lagi',
    'savedGallery': 'Gambar tersimpan di galeri!',
    'saveFailed': 'Terjadi kesalahan! Coba lagi nanti.',
    'tellUsTitle': 'Beri Tahu Kebutuhanmu',
    'tellUsSub': 'Sampaikan ide atau masalahmu',
    'requestFeature': 'Minta Fitur',
    'reportBug': 'Laporkan Bug',
    'c_character': 'Karakter',
    'c_plant': 'Tanaman',
    'justNow': 'baru saja',
    'minutesAgo': '{n} mnt lalu',
    'hoursAgo': '{n} jam lalu',
    'daysAgo': '{n} hr lalu',
    'noBuddiesYet': 'Belum ada teman',
    'noBuddiesSub': 'Menggambarlah dengan seseorang untuk menambah teman pertamamu',
    'findNewBuddy': 'Cari teman baru',
    'drewTogether': 'Menggambar bersama',
    'findingBuddies': 'Mencari teman menggambar...',
    'readyToDraw': 'Siap menggambar!',
    'readyWord': 'siap',
    'waiting': 'Menunggu...',
    'startingIn': 'Mulai dalam {n}...',
    'drawingPartner': 'Partner Menggambar',
    'doneWord': 'Selesai',
    'drawingWord': 'Menggambar',
    'premiumSub': 'Disukai seniman cilik',
    'featNoAds': 'Menggambar tanpa iklan',
    'featNewContent': 'Konten baru setiap minggu',
    'featSupport': 'Dukungan pelanggan',
    'yearly': 'Tahunan',
    'weekly': 'Mingguan',
    'save90': 'Hemat 90%',
    'justPerYear': 'Hanya {p}/tahun',
    'weekShort': 'minggu',
    'processing': 'Memproses...',
    'cancelAnytime': 'Batalkan kapan saja',
    'subDisclaimer': 'Pembayaran dimulai setelah masa uji coba gratis berakhir. Batalkan sebelum uji coba berakhir agar tidak ditagih. Langganan diperpanjang otomatis sampai kamu membatalkannya.',
    'privacy': 'Privasi',
    'terms': 'Ketentuan',
    'restorePurchase': 'Pulihkan Pembelian',
    'nothingToRestore': 'Tidak ada yang bisa dipulihkan.',
    'restoreSuccess': 'Premium kamu sudah dipulihkan!',
    'storeUnavailable': 'Toko sedang tidak tersedia. Coba lagi nanti.',
    'purchaseFailed': 'Pembelian gagal. Coba lagi.',
    'welcomePremium': 'Selamat datang di Premium! Menggambar tanpa iklan.',
    'alreadyPremium': 'Kamu sudah punya Premium.',
    'premiumActive': 'Premium Aktif ✓',
    'productNotFound': 'Langganan belum diatur di Google Play.',
    'othersNotFinished': 'Pemain lain belum selesai',
    'allFinishedTap': 'Semua sudah selesai! Ketuk →',
    'youAre1': 'KAMU JUARA 1!',
    'youAre2': 'KAMU JUARA 2!',
    'youAre3': 'KAMU JUARA 3!',
    'youAre4': 'KAMU JUARA 4!',
    'clearStepTitle': 'Hapus Langkah Ini',
    'clearStepSub': 'Hapus semua gambar di papan gambar.',
    'clearWord': 'Hapus',
    'rateForUs': 'Beri Kami Nilai',
    'rateForUsSub': 'Penilaianmu membantu kami memperbaiki pelajaran',
    'c_popular': 'Populer',
    'c_seasonal': 'Musiman',
    'randomMatch': 'Main Acak',
    'joinRoom': 'Masuk Ruang',
    'enterRoomCode': 'Masukkan kode ruang',
    'roomCodeSub': 'Kode 4 angka dari temanmu',
    'pasteClipboard': 'Tempel dari papan klip',
    'roomNotFound': 'Ruang tidak ditemukan. Periksa kode dan coba lagi.',
    'inviteFriend': 'Undang teman',
    'roomCodeTitle': 'Kode ruang',
    'waitingFriend': 'Menunggu temanmu...',
    'copyCode': 'Salin',
    'codeCopied': 'Kode disalin!',
    'shareCode': 'Gambar bareng aku di {app}! Buka Gambar Bersama → Masuk Ruang dan masukkan kode {code}',
    'joiningRoom': 'Masuk ke ruang...',
    'inviteFriendBtn': 'Undang Teman',
    'createLobby': 'Buat Lobi',
    'lobby': 'Lobi',
    'change': 'Ganti',
    'youHost': 'Kamu · tuan rumah',
    'invite': 'Undang',
    'roomCodeCaps': 'KODE RUANG',
    'roomCodeShare': 'Bagikan ID ruang tunggu ke teman.',
    'friendNearby': 'Ada teman di dekatmu?',
    'sendCode': 'Kirim kode ruangnya',
    'letsDraw': 'Ayo gambar!',
    'drawMyself': 'Aku gambar sendiri',
    'slotOpen': 'Masih ada 1 tempat',
    'pickHow': 'Pilih cara mulai.',
    'fillNow': 'Isi sekarang',
    'waitFriends': 'Tunggu teman',
    'findingBuddiesTitle': 'Mencari teman...',
    'stepsCount': '{n} langkah',
    'notOnCamera': 'Kamera mati',
    'friendStillDrawing': '{n} teman masih menggambar',
    'friendDone': 'Temanmu sudah selesai!',
    'noMessages': 'Belum ada pesan',
    'sayHi': 'Sapa teman gambarmu',
    'saySomething': 'Katakan sesuatu...',
    'react': 'Reaksi',
    'emojiTab': 'Emoji',
    'phraseTab': 'Frasa',
    'emojiOnly': 'Hanya emoji & frasa dengan teman baru',
    'choosePicture': 'Pilih gambar',
    'friendJoined': '{name} bergabung!',
    'ph1': 'Hai! 👋',
    'ph2': 'Kerja bagus!',
    'ph3': 'Lucu banget!',
    'ph4': 'Ayo!',
    'ph5': 'Warnanya bagus!',
    'ph6': 'Hampir selesai!',
    'ph7': 'Terima kasih!',
    'ph8': 'Hebat! 🎉',
    'onlineNeeded': 'Mengundang teman butuh internet.',
  },
  'hi': {
    'loading': 'लोड हो रहा है',
    'tagline': 'साथ मिलकर ड्रॉ करें',
    'chooseLanguage': 'अपनी भाषा चुनें',
    'changeAnytime': 'आप इसे कभी भी सेटिंग्स में बदल सकते हैं',
    'continue': 'जारी रखें',
    'ageTitle': 'हमें अपनी उम्र बताएं',
    'ageSub': 'अपनी रचनात्मक यात्रा शुरू करने के लिए!',
    'year': 'वर्ष',
    'purposeTitle': 'आज आप यहाँ क्यों आए हैं?',
    'purposeSub': 'जो आप पर सबसे अच्छा लागू हो, उसे चुनें',
    'p_relax': 'आराम करना और तनाव कम करना',
    'p_connect': 'दूसरों के साथ जुड़ना और ड्रॉ करना',
    'p_improve': 'अपनी ड्रॉइंग स्किल सुधारना',
    'p_kids': 'अपने बच्चों को ड्रॉ करना सिखाना',
    'p_health': 'स्वास्थ्य समस्याओं से उबरना',
    'p_other': 'अन्य',
    'interestsTitle': 'हमें अपनी रुचियाँ बताएं',
    'interestsSub': 'कम से कम 1 विकल्प चुनें',
    'i_animal': 'जानवर',
    'i_food': 'खाना',
    'i_cartoon': 'कार्टून',
    'i_anime': 'एनीमे',
    'i_kpop': 'के-पॉप आइडल',
    'i_plant': 'पौधे',
    'i_worldcup': 'विश्व कप',
    'i_seasonal': 'मौसमी',
    'goodMorning': 'सुप्रभात',
    'goodAfternoon': 'नमस्कार',
    'goodEvening': 'शुभ संध्या',
    'premium': 'प्रीमियम',
    'profile': 'प्रोफ़ाइल',
    'spentTime': 'बिताया समय',
    'lesson': 'पाठ',
    'yourLevel': 'आपका स्तर',
    'levels': 'स्तर',
    'levelDesc': 'स्तर बढ़ाने के लिए पाठ पूरे करें!',
    'lessonsNeeded': '{n} पाठ',
    'myBuddies': 'मेरे दोस्त',
    'buddiesCount': '{n} दोस्त',
    'noBuddies': 'अभी कोई दोस्त नहीं। दोस्त बनाने के लिए साथ में ड्रॉ करें!',
    'myAlbum': 'मेरा एल्बम',
    'favorite': 'पसंदीदा',
    'sortNewest': 'नवीनतम पहले',
    'sortOldest': 'सबसे पुराने पहले',
    'drawNow': 'अभी ड्रॉ करें',
    'setting': 'सेटिंग',
    'turnOffMessages': 'संदेश बंद करें',
    'music': 'संगीत',
    'soundFx': 'साउंड इफ़ेक्ट',
    'vibrate': 'कंपन',
    'language': 'भाषा',
    'share': 'दोस्तों के साथ शेयर करें',
    'rate': '5 स्टार दें',
    'feedback': 'प्रतिक्रिया',
    'policy': 'नीति',
    'checkUpdate': 'अपडेट जांचें',
    'rateTitle': 'क्या आपको यह ऐप पसंद है?',
    'rateSub': 'आपकी रेटिंग हमें ऐप को और बेहतर बनाने में मदद करेगी।',
    'rateUs': 'रेट करें',
    'thanksRating': 'आपकी रेटिंग के लिए धन्यवाद!',
    'comingSoon': 'जल्द आ रहा है!',
    'editName': 'नाम बदलें',
    'chooseAvatar': 'अवतार चुनें',
    'save': 'सहेजें',
    'cancel': 'रद्द करें',
    'shareText': 'आइए {app} पर साथ में ड्रॉ करें! यहाँ से डाउनलोड करें: {url}',
    'feedbackSubject': '{app} के लिए प्रतिक्रिया',
    'cantOpen': 'लिंक नहीं खुल सका',
    'lv_novice': 'नौसिखिया',
    'lv_apprentice': 'प्रशिक्षु',
    'lv_budding': 'उभरता',
    'lv_emerging': 'उदीयमान',
    'lv_developing': 'विकासशील',
    'lv_skilled': 'कुशल',
    'lv_proficient': 'प्रवीण',
    'lv_accomplished': 'निपुण',
    'lv_master': 'मास्टर',
    'lv_expert': 'विशेषज्ञ',
    'lv_virtuoso': 'उस्ताद',
    'lv_legendary': 'महान',
    'unlockHint': 'अनलॉक करने के लिए {n} पाठ पूरे करें',
    'levelUnlocked': 'अनलॉक हो गया!',
    'drawTogether': 'साथ में ड्रॉ करें',
    'quickMatch': 'क्विक मैच',
    'randomPlayer': 'रैंडम खिलाड़ी',
    'privateMatch': 'प्राइवेट मैच',
    'withFriends': 'दोस्तों के साथ',
    'popular': 'लोकप्रिय',
    'draw': 'ड्रॉ करें',
    'traceArt': 'ट्रेस आर्ट',
    'c_beginner': 'शुरुआती',
    'c_trending': 'ट्रेंडिंग',
    'c_neon': 'नियॉन',
    'c_xmas': 'क्रिसमस',
    'c_halloween': 'हैलोवीन',
    'emptyDrawing': 'पहले चित्र को ट्रेस करें!',
    'greatJob': 'शाबाश!',
    'lessonDone': '+1 पाठ पूरा हुआ। लेवल बढ़ाने के लिए ड्रॉ करते रहें!',
    'selectRoom': 'रूम चुनें',
    'players4': '4 खिलाड़ी',
    'players2': '2 खिलाड़ी',
    'selectTemplate': 'टेम्पलेट चुनें',
    'findingPlayers': 'दूसरे खिलाड़ी\nढूंढ रहे हैं',
    'searching': 'खोज रहे हैं',
    'matched': 'मैच\nमिल गया!',
    'leaveTitle': 'क्या आप जाना चाहते हैं?',
    'stillDrawing': 'ड्रॉ करते रहें',
    'quit': 'छोड़ें',
    'strokeWrong': 'आपको मौजूदा लाइन सही से बनानी होगी',
    'colorNow': 'आउटलाइन पूरी! रंग भरें, फिर → दबाएं',
    'waitingOthers': 'दूसरे खिलाड़ियों का इंतज़ार...',
    'results': 'नतीजे',
    'ourArtwork': 'हमारी कलाकृति',
    'playAgain': 'फिर से खेलें',
    'home': 'होम',
    'you': 'आप',
    'accuracy': 'सटीकता',
    'leftGame': 'छोड़ दिया',
    'yourPart': 'आपका हिस्सा हाइलाइट है',
    'preview': 'पूर्वावलोकन',
    'savedToAlbum': '+1 पाठ! आपकी ड्रॉइंग मेरा एल्बम में सेव हो गई।',
    'sound': 'ध्वनि',
    'exitDrawing': 'ड्रॉइंग से बाहर निकलें',
    'colorMore': 'हाइलाइट किए गए हिस्से में और रंग भरें',
    'perfectDrawing': 'परफेक्ट ड्रॉइंग',
    'greatDrawing': 'शानदार ड्रॉइंग',
    'goodDrawing': 'अच्छी ड्रॉइंग',
    'point': 'पॉइंट',
    'lines': 'लाइनें',
    'time': 'समय',
    'shareShort': 'शेयर',
    'drawAgain': 'फिर से ड्रॉ करें',
    'savedGallery': 'इमेज गैलरी में सेव हो गई!',
    'saveFailed': 'कुछ गलत हो गया! कृपया बाद में फिर कोशिश करें।',
    'tellUsTitle': 'हमें बताएं आपको क्या चाहिए',
    'tellUsSub': 'अपने सुझाव या समस्याएं बताएं',
    'requestFeature': 'फ़ीचर का अनुरोध',
    'reportBug': 'बग रिपोर्ट करें',
    'c_character': 'किरदार',
    'c_plant': 'पौधे',
    'justNow': 'अभी',
    'minutesAgo': '{n} मिनट पहले',
    'hoursAgo': '{n} घंटे पहले',
    'daysAgo': '{n} दिन पहले',
    'noBuddiesYet': 'अभी कोई दोस्त नहीं',
    'noBuddiesSub': 'अपना पहला दोस्त जोड़ने के लिए किसी के साथ ड्रॉ करें',
    'findNewBuddy': 'नया दोस्त खोजें',
    'drewTogether': 'साथ में ड्रॉ किया',
    'findingBuddies': 'ड्रॉइंग दोस्त खोज रहे हैं...',
    'readyToDraw': 'ड्रॉ करने के लिए तैयार!',
    'readyWord': 'तैयार',
    'waiting': 'इंतज़ार...',
    'startingIn': '{n} में शुरू...',
    'drawingPartner': 'ड्रॉइंग पार्टनर',
    'doneWord': 'पूरा',
    'drawingWord': 'ड्रॉ कर रहे',
    'premiumSub': 'नन्हे कलाकारों की पसंद',
    'featNoAds': 'बिना विज्ञापन ड्रॉइंग',
    'featNewContent': 'हर हफ्ते नया कंटेंट',
    'featSupport': 'ग्राहक सहायता',
    'yearly': 'सालाना',
    'weekly': 'साप्ताहिक',
    'save90': '90% बचाएं',
    'justPerYear': 'सिर्फ {p}/साल',
    'weekShort': 'हफ्ता',
    'processing': 'प्रोसेस हो रहा है...',
    'cancelAnytime': 'कभी भी रद्द करें',
    'subDisclaimer': 'फ्री ट्रायल खत्म होने के बाद भुगतान शुरू होगा। शुल्क से बचने के लिए ट्रायल खत्म होने से पहले रद्द करें। रद्द करने तक सब्सक्रिप्शन अपने आप रिन्यू होगा।',
    'privacy': 'प्राइवेसी',
    'terms': 'शर्तें',
    'restorePurchase': 'खरीद बहाल करें',
    'nothingToRestore': 'बहाल करने के लिए कुछ नहीं है।',
    'restoreSuccess': 'आपका प्रीमियम बहाल हो गया!',
    'storeUnavailable': 'स्टोर अभी उपलब्ध नहीं है। बाद में कोशिश करें।',
    'purchaseFailed': 'खरीद विफल रही। फिर से कोशिश करें।',
    'welcomePremium': 'प्रीमियम में स्वागत है! बिना विज्ञापन ड्रॉ करें।',
    'alreadyPremium': 'आपके पास पहले से प्रीमियम है।',
    'premiumActive': 'प्रीमियम सक्रिय ✓',
    'productNotFound': 'Google Play में सब्सक्रिप्शन अभी सेट नहीं हैं।',
    'othersNotFinished': 'बाकी खिलाड़ी अभी खत्म नहीं हुए',
    'allFinishedTap': 'सबने खत्म कर लिया! → दबाएं',
    'youAre1': 'आप पहले हैं!',
    'youAre2': 'आप दूसरे हैं!',
    'youAre3': 'आप तीसरे हैं!',
    'youAre4': 'आप चौथे हैं!',
    'clearStepTitle': 'यह स्टेप साफ़ करें',
    'clearStepSub': 'आर्टबोर्ड की सारी ड्रॉइंग मिटाएं।',
    'clearWord': 'साफ़ करें',
    'rateForUs': 'हमें रेट करें',
    'rateForUsSub': 'आपकी रेटिंग हमें पाठ बेहतर बनाने में मदद करती है',
    'c_popular': 'लोकप्रिय',
    'c_seasonal': 'मौसमी',
    'randomMatch': 'रैंडम मैच',
    'joinRoom': 'रूम जॉइन करें',
    'enterRoomCode': 'रूम कोड डालें',
    'roomCodeSub': 'आपके दोस्त का 4 अंकों का कोड',
    'pasteClipboard': 'क्लिपबोर्ड से पेस्ट करें',
    'roomNotFound': 'रूम नहीं मिला। कोड जांचें और फिर कोशिश करें।',
    'inviteFriend': 'दोस्त को बुलाएं',
    'roomCodeTitle': 'रूम कोड',
    'waitingFriend': 'आपके दोस्त का इंतज़ार...',
    'copyCode': 'कॉपी',
    'codeCopied': 'कोड कॉपी हो गया!',
    'shareCode': '{app} में मेरे साथ ड्रॉ करो! साथ में ड्रॉ → रूम जॉइन करें खोलें और कोड {code} डालें',
    'joiningRoom': 'रूम में जा रहे हैं...',
    'inviteFriendBtn': 'दोस्त को बुलाएं',
    'createLobby': 'लॉबी बनाएं',
    'lobby': 'लॉबी',
    'change': 'बदलें',
    'youHost': 'आप · होस्ट',
    'invite': 'बुलाएं',
    'roomCodeCaps': 'रूम कोड',
    'roomCodeShare': 'वेटिंग रूम ID दोस्तों के साथ शेयर करें।',
    'friendNearby': 'पास में कोई दोस्त है?',
    'sendCode': 'उन्हें रूम कोड भेजें',
    'letsDraw': 'चलो ड्रॉ करें!',
    'drawMyself': 'मैं अकेले ड्रॉ करूंगा',
    'slotOpen': '1 जगह अभी खाली है',
    'pickHow': 'शुरू करने का तरीका चुनें।',
    'fillNow': 'अभी भरें',
    'waitFriends': 'दोस्तों का इंतज़ार',
    'findingBuddiesTitle': 'दोस्त खोज रहे हैं...',
    'stepsCount': '{n} स्टेप',
    'notOnCamera': 'कैमरा बंद',
    'friendStillDrawing': '{n} दोस्त अभी ड्रॉ कर रहा है',
    'friendDone': 'आपके दोस्त ने खत्म कर लिया!',
    'noMessages': 'अभी कोई मैसेज नहीं',
    'sayHi': 'अपने ड्रॉइंग दोस्तों को हाय कहें',
    'saySomething': 'कुछ कहें...',
    'react': 'रिएक्ट',
    'emojiTab': 'इमोजी',
    'phraseTab': 'वाक्य',
    'emojiOnly': 'नए दोस्तों के साथ सिर्फ इमोजी और वाक्य',
    'choosePicture': 'चित्र चुनें',
    'friendJoined': '{name} आ गया!',
    'ph1': 'हाय! 👋',
    'ph2': 'बहुत बढ़िया!',
    'ph3': 'कितना प्यारा!',
    'ph4': 'चलो!',
    'ph5': 'बढ़िया रंग!',
    'ph6': 'लगभग हो गया!',
    'ph7': 'धन्यवाद!',
    'ph8': 'शाबाश! 🎉',
    'onlineNeeded': 'दोस्त को बुलाने के लिए इंटरनेट चाहिए।',
  },
};
